on: push

jobs:
    Tsinghua:
        name: 清华大学

        runs-on: windows-latest

        steps:
        - name: 拷贝内容
          uses: actions/checkout@v4

        - name: 运行两次程序
          run: |
            ./main.exe
            ./main.exe

