name: GoProgram

on:
  push:
    branches: [ "main" ]

env:
  fc_anhao: "Atletico de Madrid"
  fc_eisen: "Inter Milan"
  fc_furong: "Barcelona"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Scope
        run: |
          echo "Anhao's favourite football club is '$fc_anhao'"
          echo "Eisen's favourite football club is '$fc_eisen'"
          echo "Furong's favourite football club is '$fc_furong'"


    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v4

    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.20'

    # - name: Build
    #   run: go build -v ./...

    # - name: ls
    #   run: ls
