name: GoProgram

on: push

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
    - name: Step is going to pass
      run: echo ${{ github.repository }} Passing step
    - name: Step is going to fail
      run: exit 1
    - name: Step To run on failure
      if: ${{ failure() }}
      run: |
        curl \
        --request POST \
        --url https://api.github.com/repos/AnhaoROMA/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Issue created due to workflow failure: ${{ github.run_id }}",
          "body": "This issue was automatically created by the workflow **${{ github.workflow }}**."
        }'
