name: GoProgram

on:
  push:
    branches: [ "main" ]

env:
  user_name: "paul"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Before Modified
        run: |
          echo "$user_name"
          echo "::set-env name=user_name::zero"
          echo "$user_name"

    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v4

    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.20'

    # - name: Build
    #   run: go build -v ./...

    # - name: ls
    #   run: ls
